### ISSUE TITLE
 org.apache.xmlrpc.XmlRpcException: Unsupported Java type: class info.novatec.testit.livingdoc.server.transfer.SpecificationLocation

### ISSUE THREAD

**Issue by evictoria** [testIT-LivingDoc/livingdoc-core#26]
Hi, 

We would like to use the LivingDoc Maven plugin for our CI build. We have our specifications in Confluence. Running **mvn livingdoc:freeze** gives us:

```
info.novatec.testit.livingdoc.server.LivingDocServerException: org.apache.xmlrpc.XmlRpcException: org.apache.xmlrpc.XmlRpcException: Unsupported Java type: class info.novatec.testit.livingdoc.server.transfer.SpecificationLocation
	at info.novatec.testit.livingdoc.repository.LivingDocRepository.downloadSpecificationsDefinitions(LivingDocRepository.java:120)
	at info.novatec.testit.livingdoc.repository.LivingDocRepository.listDocuments(LivingDocRepository.java:97)
	at info.novatec.testit.livingdoc.maven.plugin.SpecificationDownloaderMojo.listDocuments(SpecificationDownloaderMojo.java:89)
	at info.novatec.testit.livingdoc.maven.plugin.SpecificationDownloaderMojo.downloadSuitesFrom(SpecificationDownloaderMojo.java:75)
	at info.novatec.testit.livingdoc.maven.plugin.SpecificationDownloaderMojo.downloadAllFrom(SpecificationDownloaderMojo.java:70)
	at info.novatec.testit.livingdoc.maven.plugin.SpecificationDownloaderMojo.downloadAllSpecs(SpecificationDownloaderMojo.java:64)
	at info.novatec.testit.livingdoc.maven.plugin.SpecificationDownloaderMojo.execute(SpecificationDownloaderMojo.java:58)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.xmlrpc.XmlRpcException: org.apache.xmlrpc.XmlRpcException: Unsupported Java type: class info.novatec.testit.livingdoc.server.transfer.SpecificationLocation
	at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeException(XmlRpcClientResponseProcessor.java:104)
	at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeResponse(XmlRpcClientResponseProcessor.java:71)
	at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:73)
	at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:194)
	at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:185)
	at info.novatec.testit.livingdoc.repository.LivingDocRepository.downloadSpecificationsDefinitions(LivingDocRepository.java:113)
	... 27 more
```

Our pom is using:

```
<plugin>
                <groupId>info.novatec.testit</groupId>
                <artifactId>livingdoc-maven</artifactId>
                <version>1.1.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <fixtureSourceDirectory>src/main/java</fixtureSourceDirectory>
                    <fixtureOutputDirectory>target/classes</fixtureOutputDirectory>
                    <specsDirectory>src/specs</specsDirectory>
                    <reportsDirectory>target/livingdoc-reports</reportsDirectory>
                    <reportsType>xml</reportsType>
                    <repositories>
                        <repository>
                            <name>Tools</name>
                            
                            <!--We use LivingDocRepository. What's the difference with AtlassianRepository?-->
                            <type>info.novatec.testit.livingdoc.repository.LivingDocRepository</type>
                            <!--Our server-->
                            <root>http://vl48/rpc/xmlrpc?handler=livingdoc1&amp;sut=petsut</root>
                            <suites>
                                <!--The name of the Repository UID-->
                                <suite>CHAMP Wiki Test-TOOLS</suite>
                            </suites>
                        </repository>
                    </repositories>
                </configuration>
                <executions>
                    <execution>
                        <id>livingdoc</id>
                        <goals>
                            <goal>compile</goal>
                            <goal>resources</goal>
                            <goal>fixture-jar</goal>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by Drakojin** [comment]
I couldn't reproduce this error. The configuration looks fine.
It may be a version mismatch.

Which Versions of Confluence and Confluence-Plugin are you using?

**Comment by evictoria** [comment]
Confluence 5.8.9 and LivingDoc plugin 1.1.0.

Thanks,
EJ

**Comment by benhamidene** [comment]
LivingDoc 1.1.+ supports confluence 5.9.3+ 
Please try upgrading confluence

**Comment by benhamidene** [comment]
HI @evictoria ,
were you able to fix the problem?
