### ISSUE TITLE
Communication problem with the runner

### ISSUE THREAD

**Issue by Lraharison** [testIT-LivingDoc/livingdoc-core#30]
Hello,
I test TestIt livingDoc and I feel we can not communicate with the runner.
I run runner in localhost with the command : 
 `/usr/java/JDK8/bin/java -jar livingdoc-remote-agent-1.1.1-complete.jar -port 56000` 
and when I execute the test I have the following errors: 
`org.apache.xmlrpc.XmlRpcException: null values not supported by XML-RPC
at org.apache.xmlrpc.XmlWriter.writeObject(XmlWriter.java:231)
at org.apache.xmlrpc.XmlWriter.writeObject(XmlWriter.java:297)
at org.apache.xmlrpc.XmlWriter.writeObject(XmlWriter.java:297)
at org.apache.xmlrpc.XmlWriter.writeObject(XmlWriter.java:297)
at org.apache.xmlrpc.XmlRpcClientRequestProcessor.encodeRequest(XmlRpcClientRequestProcessor.java:70)
[wrapped] org.apache.xmlrpc.XmlRpcClientException: Failure writing request
at org.apache.xmlrpc.XmlRpcClientRequestProcessor.encodeRequest(XmlRpcClientRequestProcessor.java:74)
at org.apache.xmlrpc.XmlRpcClientRequestProcessor.encodeRequestBytes(XmlRpcClientRequestProcessor.java:100)
at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:69)
at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:193)
at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:184)
at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:177)
at info.novatec.testit.livingdoc.server.rpc.xmlrpc.client.XmlRpcV2ClientImpl.execute(XmlRpcV2ClientImpl.java:54)
[wrapped] info.novatec.testit.livingdoc.server.rpc.xmlrpc.client.XmlRpcClientExecutorException: org.apache.xmlrpc.XmlRpcClientException: Failure writing request
at info.novatec.testit.livingdoc.server.rpc.xmlrpc.client.XmlRpcV2ClientImpl.execute(XmlRpcV2ClientImpl.java:56)`
I throw the runner or not, I still have the same problem.
About my config and test :

- The project : 
[https://drive.google.com/file/d/0B7E4-uvMfAYXUUtFZGdVa1h0WHM/view?usp=sharing](url)

- The runner :
[https://drive.google.com/file/d/0B7E4-uvMfAYXUHkyWTNNNEdPOTg/view?usp=sharing](url)

- The test: 
[https://drive.google.com/file/d/0B7E4-uvMfAYXTWhQUDJrQ0xLd0E/view?usp=sharing](url)

- the error:
[https://drive.google.com/file/d/0B7E4-uvMfAYXbnNxSm5sS1BndFU/view?usp=sharing](url)

**Comment by pkleimann** [comment]
Hi Lraharison, 
please check if the Remote API is enabled. Under [Further Configuration](https://testit-livingdoc.atlassian.net/wiki/display/CURDOC/Confluence+plugin#Confluenceplugin-FurtherConfiguration) you can activate the Remote API (XML-RPC & SOAP) of your Confluence.

**Comment by Lraharison** [comment]
Yes, it is enabled : 
[https://drive.google.com/open?id=0B7E4-uvMfAYXY1VnT1YyY01lMFU](url)

**Comment by Lraharison** [comment]
Maybe he is not find  the classpath of the project, I do not know, I tried everything but it does not work.

**Comment by pkleimann** [comment]
Hi, 
yes maybe it does not find any classes. Did you tried to add the following folders to the classpath?
/pathtoyourworkspace/target/classes
and if exists
/pathtoyourworkspace/target/libs/*.jar

**Comment by Lraharison** [comment]
I have already done it before. 

cf: [https://drive.google.com/file/d/0B7E4-uvMfAYXUUtFZGdVa1h0WHM/view?usp=sharing](https://drive.google.com/file/d/0B7E4-uvMfAYXUUtFZGdVa1h0WHM/view?usp=sharing)

**Comment by benhamidene** [comment]
which  confluence version are you using?

LivingDoc 1.1.x supports only 5.9.x

**Comment by Lraharison** [comment]
I have installed the latest version of confluence : 5.9.9
